os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.2
install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild test -scheme ULID-macOS; else swift test; fi
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash <(curl -s https://codecov.io/bash); fi
